apiVersion: v1
kind: Secret
metadata:
  name: titanic-api-secret
  namespace: titanic-api
type: Opaque
stringData:
  DATABASE_URL: "postgresql://titanic:CHANGE_ME@db-host:5432/titanic_db"
  JWT_SECRET_KEY: "CHANGE_ME_IN_OVERLAY"
