apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titanic-api
spec:
  rules:
    - host: dev.titanic-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titanic-api
                port:
                  number: 80
