apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titanic-api
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
spec:
  rules:
  - host: dev.titanic-api.example.com
