apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - path: ingress-patch.yaml

secretGenerator:
  - name: titanic-api-secret
    behavior: replace
    literals:
      - DATABASE_URL=postgresql://titanic:staging-password@staging-titanic-api-db.xxxxx.us-east-1.rds.amazonaws.com:5432/titanic_db
      - JWT_SECRET_KEY=staging-jwt-secret-key

configMapGenerator:
  - name: titanic-api-config
    behavior: merge
    literals:
      - FLASK_ENV=staging
